export const staticPoems = [
  {
    title: "The Road Not Taken",
    slug: "the-road-not-taken",
    poet: "Robert Frost",
    poetSlug: "robert-frost",
    year: 1916,
    coverImage: "/images/poetry-bg-1.jpg",
    content: [
      "Two roads diverged in a yellow wood,",
      "And sorry I could not travel both",
      "And be one traveler, long I stood",
      "And looked down one as far as I could",
      "To where it bent in the undergrowth;",
      "",
      "Then took the other, as just as fair,",
      "And having perhaps the better claim,",
      "Because it was grassy and wanted wear;",
      "Though as for that the passing there",
      "Had worn them really about the same,",
      "",
      "And both that morning equally lay",
      "In leaves no step had trodden black.",
      "Oh, I kept the first for another day!",
      "Yet knowing how way leads on to way,",
      "I doubted if I should ever come back.",
      "",
      "I shall be telling this with a sigh",
      "Somewhere ages and ages hence:",
      "Two roads diverged in a wood, and I—",
      "I took the one less traveled by,",
      "And that has made all the difference.",
    ],
  },
  {
    title: "Hope is the thing with feathers",
    slug: "hope-is-the-thing-with-feathers",
    poet: "Emily Dickinson",
    poetSlug: "emily-dickinson",
    year: 1891,
    coverImage: "/images/poetry-bg-2.jpg",
    content: [
      "Hope is the thing with feathers",
      "That perches in the soul,",
      "And sings the tune without the words,",
      "And never stops at all,",
      "",
      "And sweetest in the gale is heard;",
      "And sore must be the storm",
      "That could abash the little bird",
      "That kept so many warm.",
      "",
      "I've heard it in the chillest land,",
      "And on the strangest sea;",
      "Yet, never, in extremity,",
      "It asked a crumb of me.",
    ],
  },
  {
    title: "Invictus",
    slug: "invictus",
    poet: "William Ernest Henley",
    poetSlug: "william-ernest-henley",
    year: 1888,
    coverImage: "/images/poetry-bg-3.jpg",
    content: [
      "Out of the night that covers me,",
      "Black as the pit from pole to pole,",
      "I thank whatever gods may be",
      "For my unconquerable soul.",
      "",
      "In the fell clutch of circumstance",
      "I have not winced nor cried aloud.",
      "Under the bludgeonings of chance",
      "My head is bloody, but unbowed.",
      "",
      "Beyond this place of wrath and tears",
      "Looms but the Horror of the shade,",
      "And yet the menace of the years",
      "Finds and shall find me unafraid.",
      "",
      "It matters not how strait the gate,",
      "How charged with punishments the scroll,",
      "I am the master of my fate,",
      "I am the captain of my soul.",
    ],
  },
  {
    title: "Still I Rise",
    slug: "still-i-rise",
    poet: "Maya Angelou",
    poetSlug: "maya-angelou",
    year: 1978,
    coverImage: "/images/poetry-bg-4.jpg",
    content: [
      "You may write me down in history",
      "With your bitter, twisted lies,",
      "You may trod me in the very dirt",
      "But still, like dust, I'll rise.",
      "",
      "Does my sassiness upset you?",
      "Why are you beset with gloom?",
      "'Cause I walk like I've got oil wells",
      "Pumping in my living room.",
      "",
      "Just like moons and like suns,",
      "With the certainty of tides,",
      "Just like hopes springing high,",
      "Still I'll rise.",
    ],
  },
]

export const staticPoets = [
  {
    name: "Robert Frost",
    slug: "robert-frost",
    birthDate: "March 26, 1874",
    deathDate: "January 29, 1963",
    styles: ["Nature", "Rural Life", "American"],
    biography: [
      "Robert Frost was an American poet known for his realistic depictions of rural life and his command of American colloquial speech.",
      "One of the most popular and critically respected American poets of the twentieth century, Frost was honored frequently during his lifetime, receiving four Pulitzer Prizes for Poetry.",
      "His work frequently employed settings from rural life in New England in the early twentieth century, using them to examine complex social and philosophical themes.",
    ],
    poems: [
      {
        title: "The Road Not Taken",
        slug: "the-road-not-taken",
        year: 1916,
      },
    ],
  },
  {
    name: "Emily Dickinson",
    slug: "emily-dickinson",
    birthDate: "December 10, 1830",
    deathDate: "May 15, 1886",
    styles: ["Lyric Poetry", "Romanticism", "American"],
    biography: [
      "Emily Dickinson was an American poet who lived a largely introverted and reclusive life. She is known for her unconventional use of form and syntax.",
      "Though Dickinson was a prolific private poet, fewer than a dozen of her nearly 1,800 poems were published during her lifetime. The work that was published during her lifetime was usually altered significantly by the publishers to fit the conventional poetic rules of the time.",
      "Her poems are unique for the era in which she wrote; they contain short lines, typically lack titles, and often use slant rhyme as well as unconventional capitalization and punctuation.",
    ],
    poems: [
      {
        title: "Hope is the thing with feathers",
        slug: "hope-is-the-thing-with-feathers",
        year: 1891,
      },
    ],
  },
  {
    name: "William Ernest Henley",
    slug: "william-ernest-henley",
    birthDate: "August 23, 1849",
    deathDate: "July 11, 1903",
    styles: ["Victorian", "Inspirational"],
    biography: [
      "William Ernest Henley was an English poet, critic, and editor. He is best known for his poem 'Invictus', which he wrote while recovering from tuberculosis.",
      "At the age of 12, Henley was diagnosed with tubercular arthritis that necessitated the amputation of one of his legs just below the knee. The poem 'Invictus' is said to have developed from his experiences in hospital.",
      "Despite his disability, Henley led an active life and remained resilient. His friendship with Robert Louis Stevenson was among his most significant relationships.",
    ],
    poems: [
      {
        title: "Invictus",
        slug: "invictus",
        year: 1888,
      },
    ],
  },
  {
    name: "Maya Angelou",
    slug: "maya-angelou",
    birthDate: "April 4, 1928",
    deathDate: "May 28, 2014",
    styles: ["Civil Rights", "Autobiography", "American"],
    biography: [
      "Maya Angelou was an American poet, memoirist, and civil rights activist. She published seven autobiographies, three books of essays, several books of poetry, and is credited with a list of plays, movies, and television shows spanning over 50 years.",
      "She received dozens of awards and more than 50 honorary degrees. Angelou is best known for her series of seven autobiographies, which focus on her childhood and early adult experiences.",
      "Her first autobiography, 'I Know Why the Caged Bird Sings' (1969), tells of her life up to the age of 17 and brought her international recognition and acclaim.",
    ],
    poems: [
      {
        title: "Still I Rise",
        slug: "still-i-rise",
        year: 1978,
      },
    ],
  },
]
